from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, From, To, Subject, Content
import os
import logging
from datetime import datetime, UTC
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

logger = logging.getLogger(__name__)

class NotificationService:
    def __init__(self):
        self.sendgrid_api_key = os.environ.get('SENDGRID_API_KEY')
        # Set default email if environment variable is not set
        self.to_email = os.environ.get('TO_EMAIL', 'allualthaf42@gmail.com')
        self.sg = SendGridAPIClient(self.sendgrid_api_key) if self.sendgrid_api_key else None
        logger.info(f"Notification service initialized. Emails will be sent to: {self.to_email}")
    
    async def send_blog_notification(self, success: bool, blog_data: dict = None, error_message: str = None):
        """Send notification about blog generation status"""
        if not self.sg or not self.to_email:
            logger.error("SendGrid not configured. Skipping email notification.")
            print("❌ SendGrid not configured. Skipping email notification.")
            return
            
        try:
            if success and blog_data:
                subject = "New Blog Post Generated! 🎉"
                blog_id = str(blog_data.get('_id'))
                content = f"""
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                    <p>Hello Althaf,</p>
                    
                    <p>I'm excited to inform you that a new blog post has been generated:</p>
                    
                    <div style="margin: 20px 0; padding: 15px; background-color: #f5f5f5; border-left: 4px solid #007bff;">
                        <h3 style="color: #333; margin: 0 0 10px 0;">{blog_data['title']}</h3>
                        <p style="color: #666; margin: 0;">Generated on: {datetime.now(UTC).strftime('%B %d, %Y at %H:%M UTC')}</p>
                    </div>

                    <p>You can view this blog post at:<br>
                    <a href="https://www.althafportfolio.site/blog/{blog_id}" style="color: #007bff;">https://www.althafportfolio.site/blog/{blog_id}</a></p>
                    
                    <p style="color: #666;">This post was automatically generated by your AI blogging system.</p>
                    
                    <p>Best regards,<br>
                    Allu Bot<br>
                    Your AI Blog Assistant</p>
                </div>
                """
            else:
                subject = "❌ Blog Generation Failed"
                content = f"""
                <h2>Blog Generation Failed</h2>
                <p>The automatic blog generation failed at {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
                <p><strong>Error:</strong> {error_message}</p>
                <p>The system will retry automatically during the next health check.</p>
                """
            
            message = Mail(
                from_email=From(self.to_email, "Allu Bot"),
                to_emails=To(self.to_email),
                subject=Subject(subject),
                html_content=Content("text/html", content)
            )
            
            try:
                response = self.sg.send(message)
                print(f"SendGrid response status: {response.status_code}")
                if response.status_code not in [200, 201, 202]:
                    logger.error(f"Failed to send email notification. Status code: {response.status_code}")
                    print(f"❌ Failed to send email notification. Status code: {response.status_code}")
                else:
                    logger.info(f"Email notification sent successfully: {subject}")
                    print(f"✅ Email notification sent successfully: {subject}")
            except Exception as send_error:
                logger.error(f"SendGrid send error: {send_error}")
                print(f"❌ SendGrid send error: {send_error}")
                
        except Exception as e:
            logger.error(f"Error sending email notification: {e}")
            print(f"❌ Error sending email notification: {e}")

# Initialize global notification service
notification_service = NotificationService()