import resend
import os
import logging
from datetime import datetime, timezone
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

logger = logging.getLogger(__name__)

class NotificationService:
    def __init__(self):
        self.resend_api_key = os.environ.get('RESEND_KEY')
        # Set default email if environment variable is not set
        self.to_email = os.environ.get('TO_EMAIL', 'allualthaf42@gmail.com')
        if self.resend_api_key:
            resend.api_key = self.resend_api_key
        logger.info(f"Notification service initialized. Emails will be sent to: {self.to_email}")
    
    async def send_blog_notification(self, success: bool, blog_data: dict = None, error_message: str = None):
        """Send notification about blog generation status"""
        if not self.resend_api_key or not self.to_email:
            logger.error("Resend not configured. Skipping email notification.")
            print("❌ Resend not configured. Skipping email notification.")
            return
            
        try:
            if success and blog_data:
                subject = "New Blog Post Generated! 🎉"
                blog_id = str(blog_data.get('_id'))
                content = f"""
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                    <p>Hello Althaf,</p>
                    
                    <p>I'm excited to inform you that a new blog post has been generated:</p>
                    
                    <div style="margin: 20px 0; padding: 15px; background-color: #f5f5f5; border-left: 4px solid #007bff;">
                        <h3 style="color: #333; margin: 0 0 10px 0;">{blog_data['title']}</h3>
                        <p style="color: #666; margin: 0;">Generated on: {datetime.now(UTC).strftime('%B %d, %Y at %H:%M UTC')}</p>
                    </div>

                    <p>You can view this blog post at:<br>
                    <a href="https://www.althafportfolio.site/blog/{blog_id}" style="color: #007bff;">https://www.althafportfolio.site/blog/{blog_id}</a></p>
                    
                    <p style="color: #666;">This post was automatically generated by your AI blogging system.</p>
                    
                    <p>Best regards,<br>
                    Allu Bot<br>
                    Your AI Blog Assistant</p>
                </div>
                """
            else:
                subject = "❌ Blog Generation Failed"
                content = f"""
                <h2>Blog Generation Failed</h2>
                <p>The automatic blog generation failed at {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
                <p><strong>Error:</strong> {error_message}</p>
                <p>The system will retry automatically during the next health check.</p>
                """
            
            try:
                params = {
                    "from": "Portfolio <contact@althafportfolio.site>",
                    "to": [self.to_email],
                    "subject": subject,
                    "html": content
                }
                
                response = resend.Emails.send(params)
                logger.info(f"Email notification sent successfully: {subject}")
                print(f"✅ Email notification sent successfully: {subject}")
                print(f"Resend response: {response}")
            except Exception as send_error:
                logger.error(f"Resend send error: {send_error}")
                print(f"❌ Resend send error: {send_error}")
                
        except Exception as e:
            logger.error(f"Error sending email notification: {e}")
            print(f"❌ Error sending email notification: {e}")
    
    async def send_contact_email(self, form_data):
        """Send contact form email via Resend"""
        if not self.resend_api_key:
            raise Exception("Server is not configured for sending emails.")
            
        try:
            params = {
                "from": "Portfolio Contact <contact@althafportfolio.site>",
                "to": [self.to_email],
                "subject": f"New Message from {form_data.name}: {form_data.subject if form_data.subject else 'No Subject'}",
                "html": f"""
                    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                        <h3 style="color: #333;">New Contact Request</h3>
                        <div style="margin: 20px 0; padding: 15px; background-color: #f5f5f5; border-left: 4px solid #007bff;">
                            <p><strong>Name:</strong> {form_data.name}</p>
                            <p><strong>Email:</strong> {form_data.email}</p>
                            <p><strong>Subject:</strong> {form_data.subject if form_data.subject else 'No Subject Provided'}</p>
                            <p><strong>Message:</strong><br>{form_data.message}</p>
                        </div>
                    </div>
                """,
                "reply_to": form_data.email
            }
            
            response = resend.Emails.send(params)
            logger.info(f"Contact form email sent successfully")
            return {"message": "Email sent successfully"}
        except Exception as e:
            logger.error(f"Resend Error: {e}")
            raise Exception(f"Failed to send email via Resend provider: {e}")

# Initialize global notification service
notification_service = NotificationService()