"""
Blog Notifier Module
Sends email notifications for auto-blogger success/failure using backend/notification_service.py
"""

import os
import sys
import logging
import asyncio
from typing import Dict, Any

# Add backend to path to import notification_service
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Try importing existing service
try:
    from notification_service import NotificationService
except ImportError:
    # If standard import fails, try relative or direct file load approach if needed
    # But usually sys.path append works
    NotificationService = None

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("BlogNotifier")

class BlogNotifier:
    def __init__(self):
        self.notification_service = NotificationService() if NotificationService else None
        self.recipient = "allualthaf42@gmail.com"

    async def send_success(self, blog: Dict[str, Any], url: str):
        """Send success email"""
        if not self.notification_service:
            logger.error("NotificationService not available")
            return

        subject = f"✅ Blog Published: {blog.get('title')}"
        body = f"""
        <h1>Blog Published Successfully</h1>
        <p><strong>Title:</strong> {blog.get('title')}</p>
        <p><strong>Category:</strong> {blog.get('category')}</p>
        <p><strong>URL:</strong> <a href="{url}">{url}</a></p>
        <hr>
        <p>Generated by Auto-Blogger Agent</p>
        """
        
        try:
            await self.notification_service.send_email(
                to_email=self.recipient,
                subject=subject,
                body=body
            )
            logger.info("Success email sent")
        except Exception as e:
            logger.error(f"Failed to send success email: {e}")

    async def send_failure(self, error: str, context: str, metadata: Dict[str, Any] = None):
        """
        Send failure email with detailed context.
        Metadata keys: start_time, end_time, category, pending_title
        """
        if not self.notification_service:
            logger.error("NotificationService not available")
            return
        
        meta_html = ""
        if metadata:
            meta_html = f"""
            <h3>Failure Details</h3>
            <ul>
                <li><strong>Category:</strong> {metadata.get('category', 'Unknown')}</li>
                <li><strong>Draft Title:</strong> {metadata.get('pending_title', 'N/A')}</li>
                <li><strong>Started:</strong> {metadata.get('start_time', 'N/A')}</li>
                <li><strong>Failed:</strong> {metadata.get('end_time', 'N/A')}</li>
            </ul>
            """

        subject = f"❌ Auto-Blogger FAILED: {context} ({metadata.get('category', 'General') if metadata else 'General'})"
        body = f"""
        <h1>Auto-Blogger Failure</h1>
        <p><strong>Context:</strong> {context}</p>
        
        {meta_html}
        
        <p><strong>Error Trace:</strong></p>
        <pre style="background-color: #f8d7da; padding: 10px; border: 1px solid #f5c6cb;">{error}</pre>
        <hr>
        <p>Please check the server logs for the full stack trace.</p>
        """
        
        try:
            await self.notification_service.send_email(
                to_email=self.recipient,
                subject=subject,
                body=body
            )
            logger.info(f"Failure email sent for {context}")
        except Exception as e:
            logger.error(f"Failed to send failure email: {e}")

if __name__ == "__main__":
    # Test
    notifier = BlogNotifier()
    asyncio.run(notifier.send_failure("Test Error", "Test Script"))
