"""
Blog Notifier Module
Sends email notifications for auto-blogger success/failure using backend/notification_service.py
"""

import os
import sys
import logging
import asyncio
from typing import Dict, Any

# Add backend to path to import notification_service
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Try importing existing service
try:
    from notification_service import NotificationService
except ImportError:
    # If standard import fails, try relative or direct file load approach if needed
    # But usually sys.path append works
    NotificationService = None

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("BlogNotifier")

class BlogNotifier:
    def __init__(self):
        self.notification_service = NotificationService() if NotificationService else None
        self.recipient = os.environ.get('TO_EMAIL')
        if not self.recipient and self.notification_service:
            self.recipient = getattr(self.notification_service, 'to_email', None)
        if not self.recipient:
            self.recipient = "althafhussain.sd@gmail.com"

    async def send_success(self, blog: Dict[str, Any], url: str):
        """Send success email"""
        if not self.notification_service:
            logger.error("NotificationService not available")
            return

        import pytz
        from datetime import datetime
        
        # IST Timezone
        IST = pytz.timezone('Asia/Kolkata')
        now_ist = datetime.now(IST).strftime('%Y-%m-%d %H:%M:%S IST')
        
        # Calculate Duration
        start_str = blog.get('gen_start_time')
        end_str = blog.get('gen_end_time')
        duration_str = "Unknown"
        start_ist_str = "Unknown"
        end_ist_str = "Unknown"
        
        if start_str and end_str:
            try:
                # Parse ISO strings
                s_dt = datetime.fromisoformat(start_str)
                e_dt = datetime.fromisoformat(end_str)
                
                # Convert to IST if not already
                if s_dt.tzinfo is None: s_dt = s_dt.replace(tzinfo=pytz.utc) # assume UTC if naive
                if e_dt.tzinfo is None: e_dt = e_dt.replace(tzinfo=pytz.utc)
                
                s_ist = s_dt.astimezone(IST)
                e_ist = e_dt.astimezone(IST)
                
                start_ist_str = s_ist.strftime('%Y-%m-%d %H:%M:%S IST')
                end_ist_str = e_ist.strftime('%Y-%m-%d %H:%M:%S IST')
                
                # Duration
                diff = e_dt - s_dt
                minutes = int(diff.total_seconds() // 60)
                seconds = int(diff.total_seconds() % 60)
                duration_str = f"{minutes}m {seconds}s"
            except Exception as e:
                logger.error(f"Time calculation failed: {e}")

        subject = f"✅ Blog Published: {blog.get('title')}"
        body = f"""
        <h1>Blog Published Successfully</h1>
        <p><strong>Title:</strong> {blog.get('title')}</p>
        <p><strong>Category:</strong> {blog.get('category')}</p>
        <p><strong>URL:</strong> <a href="{url}">{url}</a></p>
        <p><strong>Published At:</strong> {now_ist}</p>
        <hr>
        <h3>⏳ Execution Stats</h3>
        <p><strong>Started:</strong> {start_ist_str}</p>
        <p><strong>Finished:</strong> {end_ist_str}</p>
        <p><strong>Duration:</strong> {duration_str}</p>
        <hr>
        <p>Generated by Auto-Blogger Agent</p>
        """
        
        try:
            await self.notification_service.send_email(
                to_email=self.recipient,
                subject=subject,
                body=body
            )
            logger.info("Success email sent")
        except Exception as e:
            logger.error(f"Failed to send success email: {e}")

    async def send_failure(self, error: str, context: str, metadata: Dict[str, Any] = None):
        """
        Send failure email with detailed context.
        Metadata keys: start_time, end_time, category, pending_title
        """
        if not self.notification_service:
            logger.error("NotificationService not available")
            return
        
        
        meta_html = ""
        if metadata:
            # Convert UTC timestamps to IST
            from datetime import datetime
            import pytz
            
            start_time_str = metadata.get('start_time', 'N/A')
            end_time_str = metadata.get('end_time', 'N/A')
            
            # Convert to IST if timestamps are datetime objects
            if start_time_str != 'N/A':
                try:
                    if isinstance(start_time_str, datetime):
                        ist = pytz.timezone('Asia/Kolkata')
                        start_time_str = start_time_str.astimezone(ist).strftime('%Y-%m-%d %H:%M:%S IST')
                except:
                    pass
            
            if end_time_str != 'N/A':
                try:
                    if isinstance(end_time_str, datetime):
                        ist = pytz.timezone('Asia/Kolkata')
                        end_time_str = end_time_str.astimezone(ist).strftime('%Y-%m-%d %H:%M:%S IST')
                except:
                    pass
            
            meta_html = f"""
            <h3>Failure Details</h3>
            <ul>
                <li><strong>Category:</strong> {metadata.get('category', 'Unknown')}</li>
                <li><strong>Draft Title:</strong> {metadata.get('pending_title', 'N/A')}</li>
                <li><strong>Started:</strong> {start_time_str}</li>
                <li><strong>Failed:</strong> {end_time_str}</li>
            </ul>
            """

        import pytz
        from datetime import datetime
        IST = pytz.timezone('Asia/Kolkata')
        now_ist = datetime.now(IST).strftime('%Y-%m-%d %H:%M:%S IST')

        subject = f"❌ Auto-Blogger FAILED: {context} ({metadata.get('category', 'General') if metadata else 'General'})"
        body = f"""
        <h1>Auto-Blogger Failure</h1>
        <p><strong>Context:</strong> {context}</p>
        <p><strong>Time:</strong> {now_ist}</p>
        
        {meta_html}
        
        <p><strong>Error Trace:</strong></p>
        <pre style="background-color: #f8d7da; padding: 10px; border: 1px solid #f5c6cb;">{error}</pre>
        <hr>
        <p>Please check the server logs for the full stack trace.</p>
        """
        
        try:
            await self.notification_service.send_email(
                to_email=self.recipient,
                subject=subject,
                body=body
            )
            logger.info(f"Failure email sent for {context}")
        except Exception as e:
            logger.error(f"Failed to send failure email: {e}")

if __name__ == "__main__":
    # Test
    notifier = BlogNotifier()
    asyncio.run(notifier.send_failure("Test Error", "Test Script"))
