name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Version Metadata
        run: |
          echo '{' > version.json
          echo '  "image_version": "${{ github.run_number }}",' >> version.json
          echo '  "build_date": "'$(date -u +'%Y-%m-%dT%H:%M:%SZ')'",' >> version.json
          echo '  "git_commit": "${{ github.sha }}"' >> version.json
          echo '}' >> version.json
          cat version.json

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            kubealthaf/portfolio-backend:latest
            kubealthaf/portfolio-backend:v${{ github.run_number }}
